import type { NextPage } from 'next'
import Head from 'next/head'
import { promises as fs } from 'node:fs'
import News from '@/contents/news.mdx'

type Props = {
  posts: Array<{
    slug: string
    meta: {
      title: string
    }
  }>
}

export const getStaticProps = async () => {
  const dataDir = 'src/articles'
  const fileNames = await fs.readdir(dataDir)
  const posts = []
  for (const fileName of fileNames) {
    const { meta } = await import(`@/articles/${fileName}`)
    const slug = fileName.replace(/\.mdx$/, '')
    posts.push({ slug, meta })
  }

  return {
    props: {
      posts,
    },
  }
}

const Home: NextPage<Props> = ({ posts }) => {
  const userName = 'ピルグリム'

  return (
    <>
      <Head>
        <title>MDX demo blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h2 className="mt-5 text-lg font-bold">新着記事</h2>
        {posts.map((post) => (
          <li key={post.slug}>
            <a href={post.slug}>{post.meta.title}</a>
          </li>
        ))}
        <h2 className="mt-5 text-lg font-bold">お知らせ</h2>
        <News userName={userName} />
      </main>
    </>
  )
}

export default Home
